Photographer.create(username: 'Valerie Elash', email: 'valerie@yourpix.com', password: 'abc123', location: 'Moldova', specialty: 'Bridal')
Client.create(username: 'Lilea Rusu', email: 'lilea@yourpix.com', password: 'abc123', location: 'Moldova')
Album.create(title: "Lilea's Bridal Photos", description: 'Beautiful shots of the bride before her big day', date: Date.new(2018, 6, 2), photographer_id: 1, client_id: 1)
Photo.create(title: 'Looking Down', description: 'Looking down holding flowers', date: Date.new(2018, 6, 2), album_id: 1).image.attach(io: File.open('app/assets/images/seed_images/bridal_1.jpg'), filename: 'bridal_1.jpg')
Photo.create(title: 'Thoughtful', description: 'Laying on a sheet looking away thoughtfully', date: Date.new(2018, 6, 2), album_id: 1).image.attach(io: File.open('app/assets/images/seed_images/bridal_2.jpg'), filename: 'bridal_2.jpg')
Photo.create(title: 'Window', description: 'Looking out through a window in black and white', date: Date.new(2018, 6, 2), album_id: 1).image.attach(io: File.open('app/assets/images/seed_images/bridal_3.jpg'), filename: 'bridal_3.jpg')
Photo.create(title: 'Closeup', description: 'Closeup of flowers and makeup', date: Date.new(2018, 6, 2), album_id: 1).image.attach(io: File.open('app/assets/images/seed_images/bridal_4.jpg'), filename: 'bridal_4.jpg')
